name: Add Dependabot PRs to Project

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  add-to-project:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to Project
        uses: actions/github-script@v7
        with:
          github-token: '${{ secrets.TOKEN }}'
          script: |
            const query = `mutation($projectId: ID! $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }`
            const variables = {
              projectId: "PVT_kwHOAK7y884A2-Fg",
              contentId: context.payload.pull_request.node_id
            };
            const result = await github.graphql(query, variables);
            console.log(result);
